In [1]:
# first neural network with keras tutorial
from numpy import loadtxt
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam 
from tensorflow.keras.utils import to_categorical
from tensorflow import constant

import keras.backend as K


In [2]:
datasets = pd.read_csv('USA_accident_dataset.csv')
# X = datasets.iloc[:, [2,3]].values
# Y = datasets.iloc[:, 4].values

datasets = datasets.drop(columns=['Start_Time', 'End_Time', 'Timezone', 'Weather_Timestamp'])





In [3]:
datasets

Severity  Distance(mi)  City  County  State  Temperature(F)  \
0             3.0         3.230     1       1      1            42.1   
1             3.0         0.500     2       2      1            37.0   
2             2.0         0.521     3       3      1            33.1   
3             2.0         0.826     4       1      1            32.0   
4             2.0         0.307     2       2      1            33.8   
...           ...           ...   ...     ...    ...             ...   
2207321       2.0         0.543  1577      53      7            86.0   
2207322       2.0         0.338  1326     503      7            70.0   
2207323       2.0         0.561   978     269      7            73.0   
2207324       2.0         0.772  2275      51      7            71.0   
2207325       2.0         0.537   793      54      7            79.0   

         Wind_Chill(F)  Humidity(%)  Pressure(in)  Visibility(mi)  ...  \
0                 36.1         58.0         29.76            10.0  ...   
1                 29.8         93.0         29.69            10.0  ...   
2                 30.0         92.0         29.63             0.5  ...   
3                 28.7        100.0         29.59             0.5  ...   
4                 29.6        100.0         29.66             3.0  ...   
...                ...          ...           ...             ...  ...   
2207321           86.0         40.0         28.92            10.0  ...   
2207322           70.0         73.0         29.39            10.0  ...   
2207323           73.0         64.0         29.74            10.0  ...   
2207324           71.0         81.0         29.62            10.0  ...   
2207325           79.0         47.0         28.63             7.0  ...   

         No_Exit  Railway  Roundabout  Station   Stop  Traffic_Calming  \
0          False    False       False    False  False            False   
1          False    False       False    False  False            False   
2          False    False       False    False  False            False   
3          False    False       False    False  False            False   
4          False    False       False    False  False            False   
...          ...      ...         ...      ...    ...              ...   
2207321    False    False       False    False  False            False   
2207322    False    False       False    False  False            False   
2207323    False    False       False    False  False            False   
2207324    False    False       False    False  False            False   
2207325    False    False       False    False  False            False   

         Traffic_Signal  Turning_Loop  Sunrise_Sunset  Time_Duration(min)  
0                 False         False               1               360.0  
1                 False         False               2               360.0  
2                 False         False               2               360.0  
3                 False         False               2               360.0  
4                 False         False               2               360.0  
...                 ...           ...             ...                 ...  
2207321           False         False               2                29.0  
2207322           False         False               2                27.0  
2207323           False         False               2                28.0  
2207324           False         False               2                29.0  
2207325           False         False               2                29.0  

[2207326 rows x 29 columns]

In [4]:
# set X and y
y = datasets['Severity']
# X = datasets[['City','State','County','Junction']].
X = datasets.drop(['Distance(mi)','Severity'], axis=1)
X = np.asarray(X).astype('int32')
y = np.asarray(y).astype('int32')



In [5]:
y = to_categorical(y)

print(datasets['Severity'].value_counts())
print(y)


2.0    2057076
3.0      64588
4.0      62106
1.0      23556
Name: Severity, dtype: int64
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [6]:


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
# model = Sequential()
# model.add(Dense(12, input_shape=(6,), activation='relu'))
# model.add(Dense(8, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))

# model = Sequential()
# model.add(Dense(8, input_dim=4, activation='relu'))
# model.add(Dense(1, activation='softmax'))

model = Sequential()
model.add(Dense(32, input_shape = (27,), activation = "relu"))
model.add(Dense(16, activation = "relu"))
model.add(Dropout(0.3))
model.add(Dense(8, activation = "relu"))
model.add(Dense(5, activation = "softmax"))
# model.compile(Adam(lr = 0.01), "categorical_crossentropy", metrics = ["accuracy"])
model.compile(loss = 'categorical_crossentropy', optimizer='sgd', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                896       
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 8)                 136       
                                                                 
 dense_3 (Dense)             (None, 5)                 45        
                                                                 
Total params: 1,605
Trainable params: 1,605
Non-trainable params: 0
_________________________________________________________________


In [17]:
# compile the keras model
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
# fit the keras model on the dataset
model.fit(x_train, y_train, epochs=10, validation_split = 0.2)

Epoch 1/10
44147/44147 [==============================] - 34s 754us/step - loss: 14.8755 - accuracy: 0.9317 - val_loss: 0.3188 - val_accuracy: 0.9318
Epoch 2/10
44147/44147 [==============================] - 34s 761us/step - loss: 0.3185 - accuracy: 0.9318 - val_loss: 0.3178 - val_accuracy: 0.9318
Epoch 3/10
44147/44147 [==============================] - 33s 746us/step - loss: 0.3181 - accuracy: 0.9318 - val_loss: 0.3175 - val_accuracy: 0.9318
Epoch 4/10
44147/44147 [==============================] - 34s 772us/step - loss: 0.3179 - accuracy: 0.9318 - val_loss: 0.3174 - val_accuracy: 0.9318
Epoch 5/10
44147/44147 [==============================] - 33s 748us/step - loss: 0.3178 - accuracy: 0.9318 - val_loss: 0.3174 - val_accuracy: 0.9318
Epoch 6/10
44147/44147 [==============================] - 33s 751us/step - loss: 0.3178 - accuracy: 0.9318 - val_loss: 0.3173 - val_accuracy: 0.9318
Epoch 7/10
44147/44147 [==============================] - 33s 739us/step - loss: 0.3177 - accuracy: 0.931

In [9]:
# evaluate the keras model
_, accuracy = model.evaluate(x_train, y_train)
print('Accuracy: %.2f' % (accuracy*100))

55184/55184 [==============================] - 31s 561us/step - loss: 0.3173 - accuracy: 0.9318
Accuracy: 93.18


In [10]:
print("Generate a prediction")
prediction = model.predict(x_test[:1])
print("prediction shape:", prediction.shape)
print(prediction)

Generate a prediction
1/1 [==============================] - 0s 59ms/step
prediction shape: (1, 5)
[[2.3715897e-05 1.1047950e-02 9.3156523e-01 2.9369367e-02 2.7993649e-02]]


In [11]:
print(y_test)

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
