In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [4]:
# read data from csv file
accident_data = pd.read_csv('US_Accidents_Dec21_updated.csv')

In [53]:
features = accident_data.iloc[:1000, [2,25,27]].values
result = accident_data.iloc[:1000, 1].values

for x in features:
    
    time = x[0].split()[1]
    time = time.replace(":","")
#     print(time)
    x[0] = int(time)
    if(x[0] is None):
        print(x)
    if(np.isnan(x[2])):
        x[2] = 0
        
    if(np.isnan(x[1])):
#         print("Is NAN")
#         print(x)
#         features = np.delete(features,i,0)
        x[1] = 0
    print(x)

[3708 10.0 10.4]
[55620 10.0 0]
[61539 10.0 0]
[65145 10.0 0]
[75343 10.0 10.4]
[81657 10.0 8.1]
[81541 3.0 2.3]
[115146 0.5 3.5]
[141957 10.0 11.5]
[151643 0.5 3.5]
[154350 3.0 4.6]
[165057 10.0 3.5]
[172739 1.8 11.5]
[173018 1.0 5.8]
[181111 10.0 0]
[181111 10.0 0]
[194742 6.0 0]
[194742 6.0 0]
[201322 1.0 8.1]
[210017 10.0 8.1]
[211010 8.0 16.1]
[213031 3.0 13.8]
[55401 1.0 9.2]
[61059 2.0 15.0]
[64632 1.5 11.5]
[71810 2.0 9.0]
[72815 1.5 10.4]
[72540 1.5 13.8]
[74449 1.5 12.7]
[74840 2.0 9.2]
[74840 3.0 12.7]
[80016 1.2 9.2]
[80255 1.0 10.4]
[81858 5.0 16.1]
[90719 1.2 8.1]
[100749 10.0 12.7]
[110949 2.5 12.7]
[112849 1.5 12.7]
[123108 1.0 13.8]
[153359 2.0 10.4]
[171240 1.0 19.6]
[171358 2.5 9.2]
[182058 2.0 12.7]
[182058 2.0 12.7]
[223748 3.0 11.5]
[223748 3.0 11.5]
[61732 4.0 11.5]
[61849 2.5 19.6]
[62948 2.0 11.5]
[81915 8.0 16.1]
[83527 1.0 10.4]
[84431 3.0 17.3]
[83916 1.5 10.4]
[83916 2.0 10.4]
[84806 2.0 4.6]
[90609 1.0 10.4]
[90609 10.0 9.2]
[90829 10.0 9.2]
[90829 10.0 9.

In [54]:
features_Train, features_Test, result_Train, result_Test = train_test_split(features, result, test_size = 0.25, random_state = 0)


In [55]:
# fitting the data (train a model)
classifier = SVC(kernel='rbf',random_state=1,C=1,gamma='auto')
classifier.fit(features_Train,result_Train)


SVC(C=1, gamma='auto', random_state=1)

In [56]:
# perform prediction on x_test data
result_pred = classifier.predict(features_Test)

In [57]:
cm = confusion_matrix(result_Test,result_pred)
print(cm)
accuracy = float(cm.diagonal().sum())/len(result_Test)
print('model accuracy is:',accuracy*100,'%')

[[154   1   0]
 [ 33   5   0]
 [ 36   0  21]]
model accuracy is: 72.0 %
